export enum GameEvent {
  CONNECT = "connect",
  JOIN_GAME = "join_game",
  PLAYER_JOINED = "player_joined",
  CREATE_GAME = "create_game",
  DISCONNECT = "disconnect",
  DISCONNECTING = "disconnecting",
  DISCONNECT_SELF = "disconnect_self",
  BANK = "bank",
  ROLL = "roll",
  BUST = "bust",
  BANK_BUST = "bank_bust",
  SELECT = "select",
  CONFIRM = "confirm",
  START_GAME = "start_game",
  NEW_GAME = "new_game",
  TIME_SET = "time_set",
  TIME_TICK = "time_tick",
  TIME_OUT = "time_out",
  PLAYER_DISCONNECTED = "player_disconnected",
  ERROR = "error",
}
